Add IEEE-754 32-bit and 64-bit floating point types
Add the IEEE-754 floating point types f32 and f64 as well as associated
literals. Due to unfamiliarity with x64 floating point instructions,
these types are only available for practical use in the C backend, where
the C compiler can be leveraged to handle arithmetic operations.
Similarly, due to the difficulty associated with accurate parsing and
formatting of floating point numbers, the C stdio routines for scanning
and formatting floating point numbers have been leveraged to implement
f32::init_from_str, f64::init_from_str, f32::format, and f64::format.

diff --git a/bin/sunder-test b/bin/sunder-test
--- a/bin/sunder-test
+++ b/bin/sunder-test
@@ -1,5 +1,5 @@
 #!/bin/sh
-set -eu
+set -e
 
 PROGNAME=$(basename "$0")
 usage() {
@@ -25,10 +25,28 @@ done
 TESTSRUN=0
 FAILURES=0
 
+contains() {
+    CONTAINS_STR="$1" # input string
+    CONTAINS_SUB="$2" # target substring
+    if [ "${CONTAINS_STR#*${CONTAINS_SUB}}" != "${CONTAINS_STR}" ]; then
+        return 0 # Input string contains target substring.
+    fi
+    return 1 # Input string does not contain target substring.
+}
+
 test() {
     TEST="$1"
 
     echo "[= TEST ${TEST} =]"
+
+    # XXX: Hack that allows conditionally skipping tests that would fail when
+    # compiled with a backend that does not support features exercised by that
+    # particular test.
+    if >/dev/null grep -i '#.*only SUNDER_BACKEND=C' "${TEST}" \
+    && ! sunder-compile -e | >/dev/null grep -i 'SUNDER_BACKEND=C'; then
+        echo '[= SKIP =]'
+        return 0
+    fi
 
     set +e
     RECEIVED=$(\
